DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (

EMP_ID INT(20) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(45) DEFAULT NULL,
LAST_NAME VARCHAR(45) DEFAULT NULL,
AGE INT(10) DEFAULT NULL,
EDUCATION VARCHAR(45) DEFAULT NULL, 
SALARY DOUBLE DEFAULT NULL,

PRIMARY KEY (`EMP_ID`) 
);