DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (

ID BIGINT(20) NOT NULL AUTO_INCREMENT,
EMP_ID VARCHAR(45) DEFAULT NULL,
FIRST_NAME VARCHAR(45) DEFAULT NULL,
LAST_NAME VARCHAR(45) DEFAULT NULL,
AGE VARCHAR(45) DEFAULT NULL,

PRIMARY KEY (`EMP_ID`) 
);