DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (

EMP_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(45) DEFAULT NULL,
LAST_NAME VARCHAR(45) DEFAULT NULL,
AGE VARCHAR(45) DEFAULT NULL,
EDUCATION VARCHAR(45) DEFAULT NULL, 
SALARY VARCHAR(45) DEFAULT NULL,

PRIMARY KEY (`EMP_ID`) 
);